#!/usr/bin/env python3
"""Create a ready-to-work-in Godot 4 project from nothing, in one command.

``godot --headless`` cannot create a project: the Project Manager is the only
supported author, so an agent driving Godot from a shell has to hand-write
``project.godot``, guess the stretch mode, invent the input map and remember
that ``ProjectSettings.save()`` drops anything that equals an engine default.
This script runs the whole of ``references/playbooks.md`` section 1 — folders,
project settings, input map, physics/render layer names, a main scene, the
shared autoloads — through the bundled dispatcher, so Godot itself writes every
setting, and then proves the result:

    godot --headless --path DEST --import
    python3 scripts/debug/validate_project.py DEST

A scaffolded project of every preset validates with zero errors and zero
warnings and boots clean through ``scripts/debug/run_project.py``.

Example::

    python3 scaffold_project.py ~/games/cave --preset pixel2d --name "Cave Diver" \\
        --autoloads game_manager,save_manager,scene_transition --with-tests --pretty

Exit codes: 0 done, 1 a step failed (the JSON names the command and its
stderr), 2 refused before touching anything (DEST already holds a project, bad
preset/size/autoload name).
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

SKILL_ROOT = Path(__file__).resolve().parents[2]
DISPATCHER = SKILL_ROOT / "scripts/core/dispatcher.gd"
TEMPLATE_DIR = SKILL_ROOT / "templates/gdscript"
VALIDATE_SCRIPT = SKILL_ROOT / "scripts/debug/validate_project.py"
RUN_PROJECT_SCRIPT = SKILL_ROOT / "scripts/debug/run_project.py"
RUN_TESTS_SCRIPT = SKILL_ROOT / "scripts/test/run_tests.py"

PRESETS = ("pixel2d", "hd2d", "3d", "ui")

# Physical keycodes (layout independent — `keycode` makes WASD unplayable on
# AZERTY). Values verified against @GlobalScope.Key on 4.7.
KEY = {
    "A": 65, "D": 68, "W": 87, "S": 83, "E": 69, "J": 74, "K": 75,
    "SPACE": 32, "ESCAPE": 4194305, "ENTER": 4194309,
    "LEFT": 4194319, "RIGHT": 4194321, "UP": 4194320, "DOWN": 4194322,
}
# @GlobalScope.JoyButton / JoyAxis, verified on 4.7.
JOY_BUTTON = {"A": 0, "B": 1, "X": 2, "Y": 3, "START": 6,
              "DPAD_UP": 11, "DPAD_DOWN": 12, "DPAD_LEFT": 13, "DPAD_RIGHT": 14}
JOY_AXIS = {"LEFT_X": 0, "LEFT_Y": 1}

PHYSICS_LAYERS = ["world", "player", "enemies", "pickups", "hitboxes", "hurtboxes"]
RENDER_LAYERS_2D = ["world", "background", "foreground"]
RENDER_LAYERS_3D = ["world", "props", "vfx"]

ICON_SVG = """<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128">
  <rect width="128" height="128" rx="24" fill="#2b2f3a"/>
  <rect x="24" y="24" width="80" height="80" rx="12" fill="#4e8cff"/>
  <rect x="44" y="44" width="16" height="16" fill="#0d1017"/>
  <rect x="68" y="44" width="16" height="16" fill="#0d1017"/>
  <rect x="44" y="76" width="40" height="8" rx="4" fill="#0d1017"/>
</svg>
"""

GITIGNORE = """# Godot 4 editor cache and imported assets. Regenerated by:
#   godot --headless --path . --import
.godot/

# Godot 3 leftovers, Android build template, Mono/C# artifacts
.import/
/android/
.mono/
data_*/
mono_crash.*.json

# Exported builds. scripts/export/add_export_preset.gd defaults every preset to
# ../build/<platform>/ (beside the project, never inside it, so the exporter
# cannot re-import its own output); this covers a build/ inside the project too.
/build/
/builds/
*.x86_64
*.exe
*.apk
*.aab
*.ipa
*.pck
*.zip

# Generated at import time from the .csv/.po sources
*.translation

# OS junk
.DS_Store
Thumbs.db

# NOTE: export_presets.cfg is deliberately NOT ignored. On Godot 4 the script
# encryption key lives in .godot/export_credentials.cfg, not in the preset file,
# so the presets are safe to commit — and every agent that clones the repo needs
# them to run scripts/export/export_project.py.
"""

GITATTRIBUTES = """# Godot's own recommendation: normalise line endings in text files.
* text=auto eol=lf

# Keep these byte-exact regardless of platform.
*.png binary
*.jpg binary
*.jpeg binary
*.webp binary
*.ogg binary
*.wav binary
*.mp3 binary
*.ttf binary
*.otf binary
*.glb binary
*.blend binary
*.res binary
*.pck binary
"""


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create a Godot 4 project (folders, settings, input map, layers, main scene, autoloads).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("dest", help="Directory to create the project in (created when missing)")
    parser.add_argument("--preset", required=True, choices=PRESETS,
                        help="pixel2d: low-res pixel art | hd2d: 1080p 2D | 3d: lit 3D starter | ui: tool/menu app")
    parser.add_argument("--name", default="", help="Project name (default: the destination folder name)")
    parser.add_argument("--size", default="", metavar="WxH",
                        help="Override the base viewport size, e.g. 480x270")
    parser.add_argument("--autoloads", default="",
                        help="Comma-separated template stems from templates/gdscript to copy and register "
                             "(default: game_manager,save_manager,scene_transition except for --preset ui)")
    parser.add_argument("--no-autoloads", action="store_true", help="Register no autoloads at all")
    parser.add_argument("--with-tests", action="store_true",
                        help="Also run scripts/test/run_tests.py DEST --init-mini")
    parser.add_argument("--godot-bin", default="", help="Godot executable (default: GODOT_BIN or godot)")
    parser.add_argument("--skip-validate", action="store_true",
                        help="Skip the closing validate_project.py pass (the JSON then has validate.skipped)")
    parser.add_argument("--pretty", action="store_true")
    return parser.parse_args(argv)


# --- preset definitions -----------------------------------------------------

def preset_config(preset: str, name: str, size: tuple[int, int] | None) -> dict:
    """Project settings, folders and scene recipe for one preset.

    Every setting name here was checked with ProjectSettings.has_setting() on
    4.7 — a misspelled name is stored without complaint and does nothing.
    """
    if preset == "pixel2d":
        width, height = size or (320, 180)
        return {
            "folders": ["scenes", "scripts", "art", "audio", "ui", "levels", "resources", "theme", "tilesets"],
            "settings": {
                "display/window/size/viewport_width": width,
                "display/window/size/viewport_height": height,
                "display/window/size/window_width_override": width * 4,
                "display/window/size/window_height_override": height * 4,
                # "viewport" renders the whole game at the low resolution and
                # scales the result, so a 1px line stays 1 game pixel wide.
                # "integer" forbids the half-pixel scale factors that make a
                # pixel grid shimmer. If the UI text looks mushy, switch
                # stretch/mode to "canvas_items" (playbooks.md section 1).
                "display/window/stretch/mode": "viewport",
                "display/window/stretch/aspect": "keep",
                "display/window/stretch/scale_mode": "integer",
                "rendering/textures/canvas_textures/default_texture_filter": 0,
                "rendering/2d/snap/snap_2d_transforms_to_pixel": True,
                "rendering/2d/snap/snap_2d_vertices_to_pixel": True,
                "gui/theme/default_font_antialiasing": 0,
                "gui/theme/default_font_hinting": 0,
                "gui/theme/default_font_subpixel_positioning": 0,
                # Compatibility is the right renderer for flat 2D: it starts
                # faster, runs on old GPUs, and it is what a web build uses
                # anyway (Godot 4.7 ships rendering_method.web =
                # "gl_compatibility" as a default override, so a forward_plus
                # project silently switches renderers in the browser). Picking
                # it everywhere means the desktop build and the web build
                # render through the same backend.
                "rendering/renderer/rendering_method": "gl_compatibility",
                "rendering/renderer/rendering_method.mobile": "gl_compatibility",
            },
            "features": "GL Compatibility",
            "actions": "game2d",
            "layers": "2d",
            "scene": scene_2d(name),
            "scene_path": "scenes/main.tscn",
        }
    if preset == "hd2d":
        width, height = size or (1920, 1080)
        return {
            "folders": ["scenes", "scripts", "art", "audio", "ui", "levels", "resources", "theme", "tilesets"],
            "settings": {
                "display/window/size/viewport_width": width,
                "display/window/size/viewport_height": height,
                "display/window/size/window_width_override": width // 2,
                "display/window/size/window_height_override": height // 2,
                # canvas_items keeps fonts and vector UI crisp at any window
                # size; expand shows more of the world instead of letterboxing.
                "display/window/stretch/mode": "canvas_items",
                "display/window/stretch/aspect": "expand",
                "rendering/renderer/rendering_method": "gl_compatibility",
                "rendering/renderer/rendering_method.mobile": "gl_compatibility",
            },
            "features": "GL Compatibility",
            "actions": "game2d",
            "layers": "2d",
            "scene": scene_2d(name),
            "scene_path": "scenes/main.tscn",
        }
    if preset == "3d":
        width, height = size or (1920, 1080)
        return {
            "folders": ["scenes", "scripts", "art", "audio", "ui", "levels", "resources", "theme", "models"],
            "settings": {
                "display/window/size/viewport_width": width,
                "display/window/size/viewport_height": height,
                "display/window/size/window_width_override": width // 2,
                "display/window/size/window_height_override": height // 2,
                "display/window/stretch/mode": "canvas_items",
                "display/window/stretch/aspect": "expand",
                "rendering/anti_aliasing/quality/msaa_3d": 2,
                "rendering/anti_aliasing/quality/screen_space_aa": 1,
            },
            "features": "Forward Plus",
            "actions": "game3d",
            "layers": "3d",
            "scene": scene_3d(name),
            "scene_path": "scenes/main.tscn",
        }
    width, height = size or (1280, 720)
    return {
        "folders": ["scenes", "scripts", "art", "audio", "ui", "resources", "theme"],
        "settings": {
            "display/window/size/viewport_width": width,
            "display/window/size/viewport_height": height,
            "display/window/stretch/mode": "canvas_items",
            "display/window/stretch/aspect": "expand",
            "display/window/size/resizable": True,
            # A menu or tool redraws only when something changes; this drops
            # idle CPU from "one core spinning" to nearly nothing.
            "application/run/low_processor_mode": True,
            "rendering/renderer/rendering_method": "gl_compatibility",
            "rendering/renderer/rendering_method.mobile": "gl_compatibility",
        },
        "features": "GL Compatibility",
        "actions": "ui",
        "layers": "none",
        "scene": scene_ui(name),
        "scene_path": "scenes/main.tscn",
    }


def boot_scenario(preset: str) -> dict:
    """A ready-to-run scenario that proves the main scene renders something.

    Written into the project as ``scenarios/boot_check.json`` so the closing
    ``next[]`` command is copy-paste runnable instead of a JSON blob to retype.
    """
    if preset == "3d":
        return {
            "scene_path": "scenes/main.tscn",
            "steps": [
                {"type": "spatial_report", "label": "boot", "ascii": True,
                 # Both of these render a black frame with no error at all,
                 # which is the single most common "my 3D scene is broken".
                 "fail_on": ["no_camera_3d", "no_light_3d"]},
            ],
        }
    if preset == "ui":
        return {
            "scene_path": "scenes/main.tscn",
            "viewport_size": {"width": 1280, "height": 720},
            "steps": [
                {"type": "ui_report", "label": "boot", "ascii": True, "fail_on": ["any"]},
            ],
        }
    return {
        "scene_path": "scenes/main.tscn",
        "steps": [
            {"type": "dump_tree", "label": "boot", "properties": ["visible", "position"]},
            {"type": "spatial_report", "label": "boot", "ascii": True},
        ],
    }


def scene_2d(name: str) -> dict:
    return {
        "scene_path": "scenes/main.tscn",
        "create_if_missing": True,
        "root_node_type": "Node2D",
        "root_node_name": "Main",
        "actions": [
            {"type": "add_node", "parent_node_path": "root", "node_type": "Node2D", "node_name": "World"},
            {"type": "add_node", "parent_node_path": "root", "node_type": "CanvasLayer", "node_name": "UI"},
            {"type": "add_node", "parent_node_path": "root/UI", "node_type": "Control", "node_name": "HUD"},
            {"type": "configure_control", "node_path": "root/UI/HUD", "layout_preset": "FULL_RECT"},
        ],
    }


def scene_3d(name: str) -> dict:
    # Camera3D + DirectionalLight3D + a WorldEnvironment with a real Environment
    # resource: without all three the first run is a black frame with no error,
    # and spatial_report's no_camera_3d / no_light_3d are exactly that check.
    return {
        "scene_path": "scenes/main.tscn",
        "create_if_missing": True,
        "root_node_type": "Node3D",
        "root_node_name": "Main",
        "actions": [
            {"type": "add_node", "parent_node_path": "root", "node_type": "Node3D", "node_name": "World"},
            {"type": "add_node", "parent_node_path": "root/World", "node_type": "WorldEnvironment",
             "node_name": "WorldEnvironment", "properties": {"environment": {
                 "__resource_type": "Environment",
                 "properties": {
                     "background_mode": 2,
                     "sky": {"__resource_type": "Sky", "properties": {
                         "sky_material": {"__resource_type": "ProceduralSkyMaterial"}}},
                     "ambient_light_source": 3,
                     "tonemap_mode": 3,
                 }}}},
            {"type": "add_node", "parent_node_path": "root/World", "node_type": "DirectionalLight3D",
             "node_name": "Sun", "properties": {
                 "position": {"__type": "Vector3", "x": 0, "y": 6, "z": 0},
                 "rotation_degrees": {"__type": "Vector3", "x": -50, "y": -35, "z": 0},
                 "shadow_enabled": True}},
            {"type": "add_node", "parent_node_path": "root/World", "node_type": "StaticBody3D",
             "node_name": "Ground", "properties": {"collision_layer": 1, "collision_mask": 1}},
            {"type": "add_node", "parent_node_path": "root/World/Ground", "node_type": "MeshInstance3D",
             "node_name": "MeshInstance3D", "properties": {"mesh": {
                 "__resource_type": "BoxMesh",
                 "properties": {"size": {"__type": "Vector3", "x": 20, "y": 1, "z": 20}}},
                 "position": {"__type": "Vector3", "x": 0, "y": -0.5, "z": 0}}},
            {"type": "add_node", "parent_node_path": "root/World/Ground", "node_type": "CollisionShape3D",
             "node_name": "CollisionShape3D", "properties": {"shape": {
                 "__resource_type": "BoxShape3D",
                 "properties": {"size": {"__type": "Vector3", "x": 20, "y": 1, "z": 20}}},
                 "position": {"__type": "Vector3", "x": 0, "y": -0.5, "z": 0}}},
            {"type": "add_node", "parent_node_path": "root", "node_type": "Camera3D", "node_name": "Camera3D",
             "properties": {
                 "position": {"__type": "Vector3", "x": 0, "y": 3, "z": 7},
                 "rotation_degrees": {"__type": "Vector3", "x": -18, "y": 0, "z": 0},
                 "current": True}},
            {"type": "add_node", "parent_node_path": "root", "node_type": "CanvasLayer", "node_name": "UI"},
            {"type": "add_node", "parent_node_path": "root/UI", "node_type": "Control", "node_name": "HUD"},
            {"type": "configure_control", "node_path": "root/UI/HUD", "layout_preset": "FULL_RECT"},
        ],
    }


def scene_ui(name: str) -> dict:
    return {
        "scene_path": "scenes/main.tscn",
        "create_if_missing": True,
        "root_node_type": "Control",
        "root_node_name": "Main",
        "actions": [
            {"type": "configure_control", "node_path": "root", "layout_preset": "FULL_RECT"},
            {"type": "add_node", "parent_node_path": "root", "node_type": "PanelContainer",
             "node_name": "Background"},
            {"type": "configure_control", "node_path": "root/Background", "layout_preset": "FULL_RECT"},
            {"type": "add_node", "parent_node_path": "root/Background", "node_type": "MarginContainer",
             "node_name": "Margin"},
            # configure_control's theme_overrides are grouped by category
            # ({"constants": {"margin_left": 32}}), not flat "constants/margin_left".
            {"type": "configure_control", "node_path": "root/Background/Margin", "theme_overrides": {
                "constants": {"margin_left": 32, "margin_top": 32,
                              "margin_right": 32, "margin_bottom": 32}}},
            {"type": "add_node", "parent_node_path": "root/Background/Margin", "node_type": "VBoxContainer",
             "node_name": "Content"},
            {"type": "configure_control", "node_path": "root/Background/Margin/Content",
             "theme_overrides": {"constants": {"separation": 16}}},
            {"type": "add_node", "parent_node_path": "root/Background/Margin/Content", "node_type": "Label",
             "node_name": "Title", "properties": {"text": name, "horizontal_alignment": 1}},
            {"type": "configure_control", "node_path": "root/Background/Margin/Content/Title",
             "theme_overrides": {"font_sizes": {"font_size": 32}}},
            {"type": "add_node", "parent_node_path": "root/Background/Margin/Content", "node_type": "Button",
             "node_name": "PrimaryButton", "properties": {"text": "Continue"}},
            {"type": "configure_control", "node_path": "root/Background/Margin/Content/PrimaryButton",
             "custom_minimum_size": {"__type": "Vector2", "x": 0, "y": 44}},
        ],
    }


def key_event(code: int) -> dict:
    return {"__resource_type": "InputEventKey", "properties": {"physical_keycode": code}}


def pad_button(index: int) -> dict:
    return {"__resource_type": "InputEventJoypadButton", "properties": {"button_index": index}}


def pad_axis(axis: int, value: float) -> dict:
    return {"__resource_type": "InputEventJoypadMotion",
            "properties": {"axis": axis, "axis_value": value}}


def input_actions(kind: str) -> dict:
    """action name -> list of typed InputEvent payloads."""
    movement = {
        "move_left": [key_event(KEY["A"]), key_event(KEY["LEFT"]),
                      pad_button(JOY_BUTTON["DPAD_LEFT"]), pad_axis(JOY_AXIS["LEFT_X"], -1.0)],
        "move_right": [key_event(KEY["D"]), key_event(KEY["RIGHT"]),
                       pad_button(JOY_BUTTON["DPAD_RIGHT"]), pad_axis(JOY_AXIS["LEFT_X"], 1.0)],
        "move_up": [key_event(KEY["W"]), key_event(KEY["UP"]),
                    pad_button(JOY_BUTTON["DPAD_UP"]), pad_axis(JOY_AXIS["LEFT_Y"], -1.0)],
        "move_down": [key_event(KEY["S"]), key_event(KEY["DOWN"]),
                      pad_button(JOY_BUTTON["DPAD_DOWN"]), pad_axis(JOY_AXIS["LEFT_Y"], 1.0)],
    }
    common = {
        "interact": [key_event(KEY["E"]), pad_button(JOY_BUTTON["X"])],
        "pause": [key_event(KEY["ESCAPE"]), pad_button(JOY_BUTTON["START"])],
    }
    if kind == "ui":
        return common
    actions = dict(movement)
    actions["jump"] = [key_event(KEY["SPACE"]), pad_button(JOY_BUTTON["A"])]
    actions["attack"] = [key_event(KEY["J"]), pad_button(JOY_BUTTON["B"])]
    actions.update(common)
    return actions


# --- helpers ----------------------------------------------------------------

class StepFailure(Exception):
    def __init__(self, step: str, command: list[str], returncode: int, stdout: str, stderr: str):
        super().__init__(step)
        self.step = step
        self.command = command
        self.returncode = returncode
        self.stdout = stdout
        self.stderr = stderr

    def payload(self) -> dict:
        return {
            "step": self.step,
            "command": " ".join(self.command),
            "returncode": self.returncode,
            "stderr": tail(self.stderr) or tail(self.stdout),
        }


def tail(text: str, lines: int = 12) -> str:
    kept = [line for line in text.splitlines() if line.strip()]
    return "\n".join(kept[-lines:])


def run(step: str, command: list[str], timeout: float = 300.0) -> subprocess.CompletedProcess[str]:
    result = subprocess.run(command, capture_output=True, text=True, check=False, timeout=timeout)
    if result.returncode != 0:
        raise StepFailure(step, command, result.returncode, result.stdout, result.stderr)
    return result


def dispatch(godot_bin: str, project: Path, operation: str, params: dict) -> dict:
    command = [godot_bin, "--headless", "--path", str(project), "--script", str(DISPATCHER),
               operation, json.dumps(params, separators=(",", ":"))]
    result = run(operation, command)
    # Not every operation prints a payload (scene_batch only logs), and the
    # dispatcher already exited non-zero if anything went wrong.
    return last_json(result.stdout) or {}


def godot_version(godot_bin: str) -> str:
    try:
        out = subprocess.run([godot_bin, "--version"], capture_output=True, text=True,
                             check=False, timeout=30).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return "4.7"
    match = re.match(r"^(\d+\.\d+)", out)
    return match.group(1) if match else "4.7"


def autoload_name_for(template: Path) -> str | None:
    """`# Autoload: YES, as \\`GameManager\\`` in the template header, or None.

    Reading the name out of the file keeps this in step with templates other
    work packages add, instead of a table here that silently goes stale.
    """
    try:
        header = template.read_text(encoding="utf-8")[:4000]
    except OSError:
        return None
    match = re.search(r"#\s*Autoload:\s*YES,\s*as\s*`([A-Za-z_][A-Za-z0-9_]*)`", header)
    if match:
        return match.group(1)
    if re.search(r"#\s*Autoload:\s*YES", header):
        return "".join(part.capitalize() for part in template.stem.split("_"))
    return None


def available_autoloads() -> dict[str, str]:
    found: dict[str, str] = {}
    if not TEMPLATE_DIR.is_dir():
        return found
    for template in sorted(TEMPLATE_DIR.glob("*.gd")):
        name = autoload_name_for(template)
        if name:
            found[template.stem] = name
    return found


def parse_size(raw: str) -> tuple[int, int] | None:
    if not raw:
        return None
    match = re.fullmatch(r"\s*(\d+)\s*[xX*]\s*(\d+)\s*", raw)
    if not match:
        raise SystemExit(refuse(f"--size must look like WxH, e.g. 320x180 (got: {raw!r})"))
    width, height = int(match.group(1)), int(match.group(2))
    if width < 16 or height < 16 or width > 16384 or height > 16384:
        raise SystemExit(refuse(f"--size must be between 16x16 and 16384x16384 (got: {width}x{height})"))
    return width, height


def refuse(message: str, **extra: object) -> int:
    payload = {"ok": False, "error": message}
    payload.update(extra)
    print(json.dumps(payload, indent=2))
    return 2


# --- main -------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv if argv is not None else sys.argv[1:])
    godot_bin = args.godot_bin or os.environ.get("GODOT_BIN", "godot")
    dest = Path(args.dest).expanduser().resolve()
    project_file = dest / "project.godot"
    if project_file.is_file():
        return refuse(
            f"{project_file} already exists; scaffold_project.py never writes into an existing project. "
            "Point --dest at a new directory, or edit this one with "
            f"project_batch / scene_batch (see {SKILL_ROOT / 'references/playbooks.md'} section 1).",
            project_path=str(dest))
    if dest.exists() and not dest.is_dir():
        return refuse(f"{dest} exists and is not a directory")
    if shutil.which(godot_bin) is None:
        return refuse(f"Godot executable was not found: {godot_bin}. "
                      "Install Godot 4.7 or pass --godot-bin /path/to/godot.")

    size = parse_size(args.size)
    name = args.name.strip() or dest.name
    if '"' in name or "\n" in name:
        return refuse('--name must not contain quotes or newlines')

    catalog = available_autoloads()
    if args.no_autoloads:
        requested: list[str] = []
    elif args.autoloads.strip():
        requested = [item.strip() for item in args.autoloads.split(",") if item.strip()]
    elif args.preset == "ui":
        requested = []
    else:
        requested = ["game_manager", "save_manager", "scene_transition"]
    unknown = [item for item in requested if item not in catalog]
    if unknown:
        return refuse(
            f"Unknown autoload template(s): {', '.join(unknown)}. "
            f"Templates that declare 'Autoload: YES' in {TEMPLATE_DIR}: {', '.join(sorted(catalog)) or '(none)'}",
            available_autoloads=sorted(catalog))

    config = preset_config(args.preset, name, size)
    created: list[str] = []
    try:
        created += write_skeleton(dest, name, args.preset, config, godot_bin)
        # First import builds .godot/ and imports icon.svg, so the project is a
        # real project before any dispatcher operation touches it.
        run("import", [godot_bin, "--headless", "--path", str(dest), "--import"])

        autoloads = copy_autoloads(dest, requested, catalog)
        created += [f"scripts/{item}.gd" for item in requested]
        if requested:
            # A copied script's `class_name` stays invisible to every other
            # script until --import refreshes .godot/global_script_class_cache.
            run("import", [godot_bin, "--headless", "--path", str(dest), "--import"])

        buses: list[str] = []
        if "AudioManager" in autoloads.values():
            # audio_manager.gd routes to the Music and SFX buses; registering it
            # before they exist makes every player fall back to Master and the
            # validation run carries a warning.
            dispatch(godot_bin, dest, "setup_audio_buses", {
                "buses": [
                    {"name": "Master", "volume_db": 0.0},
                    {"name": "Music", "send": "Master", "volume_db": -6.0},
                    {"name": "SFX", "send": "Master", "volume_db": -3.0},
                ],
                "save_path": "audio/default_bus_layout.tres",
                "set_project_setting": True,
            })
            buses = ["Master", "Music", "SFX"]
            created.append("audio/default_bus_layout.tres")

        actions = settings_actions(config) + input_actions_batch(config) + layer_actions(config)
        for stem, autoload in autoloads.items():
            actions.append({"type": "add_autoload", "autoload_name": autoload,
                            "path": f"res://scripts/{stem}.gd", "singleton": True})
        dispatch(godot_bin, dest, "project_batch", {"actions": actions})

        dispatch(godot_bin, dest, "scene_batch", config["scene"])
        created.append(config["scene_path"])
        dispatch(godot_bin, dest, "project_batch", {
            "actions": [{"type": "set_main_scene", "scene_path": "res://" + config["scene_path"]}]})
        normalize_int_settings(dest / "project.godot", config["settings"])

        tests: dict = {"initialized": False}
        if args.with_tests:
            result = run("run_tests --init-mini",
                         [sys.executable, str(RUN_TESTS_SCRIPT), str(dest), "--init-mini",
                          "--godot-bin", godot_bin])
            tests = {"initialized": True, "detail": last_json(result.stdout) or {}}
            created += ["tests/test_case.gd", "tests/test_example.gd"]

        run("import", [godot_bin, "--headless", "--path", str(dest), "--import"])
    except StepFailure as failure:
        print(json.dumps({"ok": False, "preset": args.preset, "project_path": str(dest),
                          "created": sorted(set(created)), "failed": failure.payload()},
                         indent=2 if args.pretty else None))
        return 1
    except subprocess.TimeoutExpired as expired:
        print(json.dumps({"ok": False, "preset": args.preset, "project_path": str(dest),
                          "error": f"timed out: {expired.cmd}"}, indent=2 if args.pretty else None))
        return 1

    validate: dict = {"skipped": True}
    if not args.skip_validate:
        validate = validate_project(dest, godot_bin)

    payload = {
        "ok": bool(validate.get("ok", True)),
        "preset": args.preset,
        "project_path": str(dest),
        "name": name,
        "created": sorted(set(created)),
        "settings_applied": config["settings"],
        "input_actions": sorted(input_actions(config["actions"])),
        "autoloads": list(autoloads.values()),
        "autoload_scripts": {name: f"res://scripts/{stem}.gd" for stem, name in autoloads.items()},
        "audio_buses": buses,
        "main_scene": "res://" + config["scene_path"],
        "tests": tests,
        "validate": validate,
        "next": next_commands(dest, args.preset),
    }
    print(json.dumps(payload, indent=2 if args.pretty else None))
    return 0 if payload["ok"] else 1


def last_json(stdout: str) -> dict | None:
    for line in reversed(stdout.splitlines()):
        stripped = line.strip()
        if stripped.startswith("{") and stripped.endswith("}"):
            try:
                return json.loads(stripped)
            except json.JSONDecodeError:
                return None
    return None


def write_skeleton(dest: Path, name: str, preset: str, config: dict, godot_bin: str) -> list[str]:
    created: list[str] = []
    dest.mkdir(parents=True, exist_ok=True)
    for folder in config["folders"]:
        (dest / folder).mkdir(parents=True, exist_ok=True)
        # Git drops empty directories; a dot-file is also skipped by Godot's
        # filesystem scanner, so it never shows up as an unimportable asset.
        (dest / folder / ".gitkeep").write_text("", encoding="utf-8")
        created.append(folder + "/")

    version = godot_version(godot_bin)
    features = f'PackedStringArray("{version}", "{config["features"]}")'
    (dest / "project.godot").write_text(
        "; Engine configuration file.\n"
        "; Written by scripts/project/scaffold_project.py, then rewritten by\n"
        "; ProjectSettings.save() through the project_batch operation.\n"
        "\n"
        "config_version=5\n"
        "\n"
        "[application]\n"
        "\n"
        f'config/name="{name}"\n'
        f"config/features={features}\n"
        'config/icon="res://icon.svg"\n',
        encoding="utf-8")
    created.append("project.godot")
    (dest / "icon.svg").write_text(ICON_SVG, encoding="utf-8")
    created.append("icon.svg")
    (dest / ".gitignore").write_text(GITIGNORE, encoding="utf-8")
    created.append(".gitignore")
    (dest / ".gitattributes").write_text(GITATTRIBUTES, encoding="utf-8")
    created.append(".gitattributes")
    (dest / "scenarios").mkdir(parents=True, exist_ok=True)
    (dest / "scenarios/boot_check.json").write_text(
        json.dumps(boot_scenario(preset), indent=2) + "\n", encoding="utf-8")
    created.append("scenarios/boot_check.json")
    return created


def normalize_int_settings(project_file: Path, settings: dict) -> None:
    """Rewrite ``viewport_width=320.0`` back to ``viewport_width=320``.

    JSON has a single number type, so every integer that travels through the
    dispatcher arrives in GDScript as a float and ``ProjectSettings.save()``
    writes ``320.0`` where the editor writes ``320``. The engine converts on
    read, so nothing breaks — but the file is what the next human and the next
    agent copy from, so it should say what the editor says. This runs after the
    last ``project_batch``; once the file holds an int, Godot loads it as an int
    and every later save keeps it.
    """
    wanted: dict[tuple[str, str], int] = {}
    for name, value in settings.items():
        if isinstance(value, bool) or not isinstance(value, int) or "/" not in name:
            continue
        section, _, key = name.partition("/")
        wanted[(section, key)] = value
    if not wanted or not project_file.is_file():
        return
    section = ""
    out: list[str] = []
    changed = False
    for line in project_file.read_text(encoding="utf-8").splitlines(keepends=True):
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            section = stripped[1:-1]
        elif "=" in stripped and not stripped.startswith(";"):
            key = stripped.split("=", 1)[0].strip()
            target = wanted.get((section, key))
            if target is not None and stripped.split("=", 1)[1].strip() == f"{float(target)!r}":
                line = f"{key}={target}\n"
                changed = True
        out.append(line)
    if changed:
        project_file.write_text("".join(out), encoding="utf-8")


def copy_autoloads(dest: Path, requested: list[str], catalog: dict[str, str]) -> dict[str, str]:
    autoloads: dict[str, str] = {}
    scripts = dest / "scripts"
    scripts.mkdir(parents=True, exist_ok=True)
    for stem in requested:
        shutil.copyfile(TEMPLATE_DIR / f"{stem}.gd", scripts / f"{stem}.gd")
        autoloads[stem] = catalog[stem]
    return autoloads


def settings_actions(config: dict) -> list[dict]:
    return [{"type": "set_setting", "name": key, "value": value}
            for key, value in config["settings"].items()]


def input_actions_batch(config: dict) -> list[dict]:
    actions: list[dict] = []
    for action_name, events in sorted(input_actions(config["actions"]).items()):
        actions.append({"type": "add_input_action", "action_name": action_name, "replace": True})
        for event in events:
            actions.append({"type": "add_input_event", "action_name": action_name, "event": event})
    return actions


def layer_actions(config: dict) -> list[dict]:
    kind = config["layers"]
    if kind == "none":
        return []
    physics = f"{kind}_physics"
    render = f"{kind}_render"
    names = RENDER_LAYERS_2D if kind == "2d" else RENDER_LAYERS_3D
    actions = [{"type": "set_layer_name", "layer_type": physics, "layer": index + 1, "layer_name": layer}
               for index, layer in enumerate(PHYSICS_LAYERS)]
    actions += [{"type": "set_layer_name", "layer_type": render, "layer": index + 1, "layer_name": layer}
                for index, layer in enumerate(names)]
    return actions


def validate_project(dest: Path, godot_bin: str) -> dict:
    # --warnings-as-errors: a scaffold that starts with yellow triangles teaches
    # the agent to ignore them.
    result = subprocess.run([sys.executable, str(VALIDATE_SCRIPT), str(dest),
                             "--godot-bin", godot_bin, "--warnings-as-errors"],
                            capture_output=True, text=True, check=False, timeout=600)
    payload = last_json(result.stdout)
    if payload is None:
        return {"ok": False, "counts": {}, "error": tail(result.stderr) or tail(result.stdout)}
    return {"ok": bool(payload.get("ok")), "counts": payload.get("counts", {}),
            "diagnostics": payload.get("diagnostics", [])[:10]}


def next_commands(dest: Path, preset: str) -> list[str]:
    return [
        f"python3 {RUN_PROJECT_SCRIPT} {dest} --quit-after 60 --timeout 60 --pretty",
        f"python3 {SKILL_ROOT / 'scripts/debug/run_scenario.py'} {dest} "
        f"{dest / 'scenarios/boot_check.json'} --pretty",
        f"python3 {VALIDATE_SCRIPT} {dest} --pretty",
        (f"godot --headless --path {dest} --script {DISPATCHER} "
         f"add_export_preset '{{\"platform\":\"web\"}}'"),
        f"cat {SKILL_ROOT / 'references/playbooks.md'}   # section 2 adds a player",
    ]


if __name__ == "__main__":
    raise SystemExit(main())
